[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "libxkbcommon", "libxcomposite", "libxdamage", "libxrandr", "mesa", "egl-wayland", "libxshmfence", "cups", "cairo", "pango", "gdk-pixbuf", "gtk3"]

[phases.build]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm install"]
