[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "libxkbcommon", "libxcomposite", "libxdamage", "libxrandr", "mesa", "egl-wayland", "libxshmfence", "cups"]

[phases.build]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm install"]
